# Generated by Django 4.2.29 on 2026-03-11 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('TenDangNhap', models.CharField(max_length=100, unique=True)),
                ('VaiTro', models.CharField(choices=[('SinhVien', 'Sinh viên'), ('Admin', 'Quản trị viên'), ('ThuKy', 'Thư ký'), ('ThamDinh', 'Thẩm định')], default='SinhVien', max_length=20)),
                ('TrangThai', models.CharField(choices=[('Active', 'Hoạt động'), ('Inactive', 'Không hoạt động')], default='Active', max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
                ('NgayCapNhat', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Tài khoản',
                'db_table': 'TaiKhoan',
            },
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoTen', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
                ('TaiKhoan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nguoi_dung', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Người dùng quản trị',
                'db_table': 'NguoiDung',
            },
        ),
    ]
