# Generated by Django 6.0.3 on 2026-04-17 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
                ('HetHan', models.DateTimeField()),
                ('DaSuDung', models.BooleanField(default=False)),
                ('TaiKhoan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token đặt lại mật khẩu',
                'db_table': 'PasswordResetToken',
            },
        ),
    ]
