# Generated by Django 4.2.29 on 2026-03-11 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HoTen', models.CharField(max_length=100)),
                ('MaSV', models.CharField(max_length=20, unique=True)),
                ('Lop', models.CharField(max_length=50)),
                ('Khoa', models.CharField(max_length=100)),
                ('DiemTBC', models.FloatField(default=0)),
                ('DiemRenLuyen', models.IntegerField(default=0)),
                ('DiemTheDuc', models.FloatField(default=0)),
                ('TrinhDoNgoaiNgu', models.CharField(choices=[('None', 'Chưa có'), ('B1', 'B1'), ('B2', 'B2'), ('IELTS', 'IELTS'), ('TOEIC', 'TOEIC'), ('Other', 'Khác')], default='None', max_length=20)),
                ('GPANgoaiNgu', models.FloatField(default=0)),
                ('LaDangVien', models.BooleanField(default=False)),
                ('KhongViPham', models.BooleanField(default=True)),
                ('TrangThaiHoSo', models.CharField(choices=[('Draft', 'Chưa nộp'), ('Submitted', 'Đã nộp'), ('Processing', 'Đang xét'), ('Approved', 'Đã duyệt'), ('Rejected', 'Từ chối')], default='Draft', max_length=20)),
                ('TongDiem', models.FloatField(default=0)),
                ('PhanHoiChung', models.CharField(blank=True, max_length=500, null=True)),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
                ('NgayCapNhat', models.DateTimeField(auto_now=True)),
                ('TaiKhoan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sinh_vien', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sinh viên',
                'db_table': 'SinhVien',
            },
        ),
        migrations.CreateModel(
            name='XacMinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TruongDuLieu', models.CharField(choices=[('gpa', 'Điểm trung bình (GPA)'), ('trainingPoints', 'Điểm rèn luyện'), ('peScore', 'Điểm thể dục'), ('english', 'Trình độ ngoại ngữ'), ('partyMember', 'Đảng viên')], max_length=50)),
                ('TrangThai', models.CharField(choices=[('Pending', 'Chờ xác minh'), ('Approved', 'Đã xác minh'), ('Rejected', 'Từ chối'), ('NeedsExplanation', 'Cần giải trình')], default='Pending', max_length=30)),
                ('PhanHoi', models.CharField(blank=True, max_length=500, null=True)),
                ('NgayCapNhat', models.DateTimeField(auto_now=True)),
                ('SinhVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xac_minh', to='students.sinhvien')),
            ],
            options={
                'verbose_name': 'Xác minh',
                'db_table': 'XacMinh',
                'unique_together': {('SinhVien', 'TruongDuLieu')},
            },
        ),
    ]
