# Generated by Django 4.2.29 on 2026-03-16 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_rename_phanhoi_xacminh_phanhoiadmin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichSuHoSo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrangThaiTruoc', models.CharField(max_length=20)),
                ('TrangThaiSau', models.CharField(max_length=20)),
                ('NoiDung', models.CharField(blank=True, max_length=500)),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
                ('NguoiThucHien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('SinhVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su', to='students.sinhvien')),
            ],
            options={
                'verbose_name': 'Lịch sử hồ sơ',
                'db_table': 'LichSuHoSo',
                'ordering': ['-NgayTao'],
            },
        ),
    ]
