# Generated by Django 4.2.29 on 2026-03-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_xacminh_ngaygiaitrinh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xacminh',
            name='NgayGiaiTrinh',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày gửi giải trình'),
        ),
    ]
