# Generated by Django 6.0.3 on 2026-04-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_add_ngay_giai_trinh_to_xac_minh'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinhvien',
            name='Email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email sinh viên'),
        ),
    ]
