# Generated by Django 4.2.29 on 2026-03-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaiViet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TieuDe', models.CharField(max_length=300)),
                ('NoiDung', models.TextField()),
                ('NgayDang', models.DateField(auto_now_add=True)),
                ('TrangThai', models.CharField(choices=[('draft', 'Nháp'), ('published', 'Đã đăng')], default='draft', max_length=20)),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
                ('NgayCapNhat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bài viết',
                'db_table': 'BaiViet',
                'ordering': ['-NgayDang'],
            },
        ),
        migrations.CreateModel(
            name='VinhDanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenSinhVien', models.CharField(max_length=100)),
                ('ThanhTich', models.CharField(max_length=200)),
                ('NoiDung', models.TextField(blank=True, null=True)),
                ('HinhAnh', models.ImageField(blank=True, null=True, upload_to='vinh_danh/')),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vinh danh',
                'db_table': 'VinhDanh',
                'ordering': ['-NgayTao'],
            },
        ),
    ]
