# Generated by Django 4.2.29 on 2026-03-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinhdanh',
            name='HinhAnh',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
