# Generated by Django 4.2.29 on 2026-03-11 10:35

from django.db import migrations, models
import django.db.models.deletion
import evidences.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criteria', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinhChung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenMinhChung', models.CharField(max_length=200)),
                ('CapDo', models.CharField(choices=[('Cấp Khoa/CLB', 'Cấp Khoa/CLB'), ('Cấp Trường/Phường/Xã', 'Cấp Trường/Phường/Xã'), ('Cấp ĐHĐN', 'Cấp ĐHĐN'), ('Cấp Tỉnh/Thành phố', 'Cấp Tỉnh/Thành phố'), ('Cấp Trung ương', 'Cấp Trung ương')], max_length=50)),
                ('LoaiMinhChung', models.CharField(choices=[('Không Sqđ/GCN thường', 'Không Sqđ/GCN thường'), ('Có Sqđ/GCN có mã số', 'Có Sqđ/GCN có mã số'), ('Giấy khen/Bằng khen', 'Giấy khen/Bằng khen')], max_length=50)),
                ('SoQuyetDinh', models.CharField(blank=True, max_length=100, null=True)),
                ('DuongDanFile', models.FileField(blank=True, null=True, upload_to=evidences.models.minh_chung_upload_path)),
                ('TenFile', models.CharField(blank=True, max_length=200, null=True)),
                ('NgayNop', models.DateField(auto_now_add=True)),
                ('Diem', models.FloatField(default=0)),
                ('TrangThai', models.CharField(choices=[('Pending', 'Chờ duyệt'), ('Approved', 'Đã duyệt'), ('Rejected', 'Từ chối'), ('NeedsExplanation', 'Cần giải trình')], default='Pending', max_length=30)),
                ('PhanHoiAdmin', models.CharField(blank=True, max_length=500, null=True)),
                ('GiaiTrinhSV', models.CharField(blank=True, max_length=500, null=True)),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
                ('NgayCapNhat', models.DateTimeField(auto_now=True)),
                ('SinhVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minh_chung', to='students.sinhvien')),
                ('TieuChi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minh_chung', to='criteria.tieuchi')),
            ],
            options={
                'verbose_name': 'Minh chứng',
                'db_table': 'MinhChung',
                'ordering': ['-NgayTao'],
            },
        ),
    ]
