# Generated by Django 4.2.29 on 2026-03-11 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhomTieuChi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenNhom', models.CharField(max_length=100, unique=True)),
                ('MoTa', models.CharField(blank=True, max_length=500, null=True)),
                ('ThuTu', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Nhóm tiêu chí',
                'db_table': 'NhomTieuChi',
                'ordering': ['ThuTu'],
            },
        ),
        migrations.CreateModel(
            name='TieuChi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MoTa', models.CharField(max_length=500)),
                ('LoaiTieuChi', models.CharField(choices=[('Cung', 'Cứng (bắt buộc)'), ('Cong', 'Cộng (linh hoạt)')], default='Cong', max_length=10)),
                ('Diem', models.FloatField(blank=True, null=True)),
                ('CoSoQuyetDinh', models.BooleanField(default=False)),
                ('SoLuongToiThieu', models.IntegerField(blank=True, null=True)),
                ('ThuTu', models.IntegerField(default=0)),
                ('NhomTieuChi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tieu_chi', to='criteria.nhomtieuchi')),
            ],
            options={
                'verbose_name': 'Tiêu chí',
                'db_table': 'TieuChi',
                'ordering': ['ThuTu'],
            },
        ),
        migrations.CreateModel(
            name='DiemTheoCapDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CapDo', models.CharField(choices=[('Cấp Khoa/CLB', 'Cấp Khoa/CLB'), ('Cấp Trường/Phường/Xã', 'Cấp Trường/Phường/Xã'), ('Cấp ĐHĐN', 'Cấp ĐHĐN'), ('Cấp Tỉnh/Thành phố', 'Cấp Tỉnh/Thành phố'), ('Cấp Trung ương', 'Cấp Trung ương')], max_length=50)),
                ('Diem', models.FloatField()),
                ('TieuChi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diem_cap_do', to='criteria.tieuchi')),
            ],
            options={
                'verbose_name': 'Điểm theo cấp độ',
                'db_table': 'DiemTheoCapDo',
                'unique_together': {('TieuChi', 'CapDo')},
            },
        ),
    ]
