# Generated by Django 4.2.29 on 2026-03-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tieuchi',
            name='MaTieuChi',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
