# Generated by Django 4.2.29 on 2026-04-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0002_tieuchi_matieuchi'),
    ]

    operations = [
        migrations.AddField(
            model_name='tieuchi',
            name='KhongSoQuyetDinh',
            field=models.BooleanField(default=True),
        ),
    ]
